name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: requirements
    attributes:
      label: Basic Troubleshooting Steps
      description: Please confirm that you have taken these basic troubleshooting steps.
      options:
        - label: The issue exists in the latest release.
          required: true
        - label: The issue exists in the latest development version (`main` or `develop` branch).
          required: false
        - label: I have searched the existing issues for this problem and it has not been reported yet.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How can the problem be reproduced?
      description: Please give step by step instructions on how to trigger the problem.
      placeholder: "1. Go outside.
        \n2. Touch Grass.
        \n3. Observe wet fingers from precipitation."
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Do you have any extra information that could be useful?
      description: Add anything else that might be useful here, e.g. log output or information about anything in your setup that is unusual.
